//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_UrunProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Urun()
        {
            this.Tbl_Satıslar = new HashSet<Tbl_Satıslar>();
        }
    
        public int urunId { get; set; }
        public string urunAd { get; set; }
        public string urunMarka { get; set; }
        public Nullable<short> urunStok { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public Nullable<bool> urunDurum { get; set; }
        public Nullable<int> urunKategori { get; set; }
    
        public virtual Tbl_Kategoriler Tbl_Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satıslar> Tbl_Satıslar { get; set; }
    }
}
